--PROCEDURE UPDATE CONTATO
IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'UPDATE_CONTATO')
DROP PROCEDURE UPDATE_CONTATO
GO

CREATE PROCEDURE UPDATE_CONTATO(@NOME_CONTATO VARCHAR(100), @ID_CONTATO INT)
AS
BEGIN
    DECLARE  @CONTATO_INT INT
	DECLARE  @RET_VALUE INT

	SET @CONTATO_INT = (SELECT COUNT(*) FROM TB_CONTATOS WHERE ID_CONTATO = @CONTATO_INT)
	IF(@CONTATO_INT = 0)
	BEGIN
	   SET @RET_VALUE = -1
    END
	ELSE
	BEGIN TRY
	    UPDATE TB_CONTATOS SET NOME_CONTATO =  @NOME_CONTATO WHERE ID_CONTATO =  @ID_CONTATO
		SET @RET_VALUE = @ID_CONTATO
	END TRY
	BEGIN CATCH
	    SET @RET_VALUE = 0 
	END CATCH
END
GO

--PROCEDURE UPDATE EMAIL
IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'UPDATE_EMAIL')
DROP PROCEDURE UPDATE_EMAIL
GO

CREATE PROCEDURE UPDATE_EMAIL(@EMAIL VARCHAR(200), @ID_EMAIL INT)
AS
BEGIN
    DECLARE  @EMAIL_INT INT
	DECLARE @RET_VALUE INT
	SET @EMAIL_INT = (SELECT COUNT(*) FROM TB_EMAIL WHERE ID_EMAIL = @ID_EMAIL)
	IF(@EMAIL_INT = 0)
	BEGIN
	   SET @RET_VALUE = -1
    END
	ELSE
	BEGIN TRY
	    UPDATE TB_EMAIL SET EMAIL = @EMAIL WHERE ID_EMAIL = @ID_EMAIL
		SET @RET_VALUE =  @ID_EMAIL
	END TRY
	BEGIN CATCH
	    SET @RET_VALUE =  0 
	END CATCH
END
GO

--PROCEDURE UPDATE TELEFONE
IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'UPDATE_TELEFONE')
DROP PROCEDURE UPDATE_TELEFONE
GO

CREATE PROCEDURE UPDATE_TELEFONE(@TELEFONE VARCHAR(14), @ID_TELEFONE INT)
AS
BEGIN
    DECLARE  @TELEFONE_INT INT
	DECLARE @RET_VALUE INT
	SET @TELEFONE_INT = (SELECT COUNT(*) FROM TB_TELEFONE WHERE ID_TELEFONE = @ID_TELEFONE)
	IF(@TELEFONE_INT = 0)
	BEGIN
	   SET @RET_VALUE = -1
    END
	ELSE
	BEGIN TRY
	    UPDATE TB_TELEFONE SET TELEFONE = @TELEFONE WHERE ID_TELEFONE = @ID_TELEFONE
		SET @RET_VALUE = @ID_TELEFONE
	END TRY
	BEGIN CATCH
	    SET @RET_VALUE = 0 
	END CATCH
END