--PROCEDURE CONSULTA CONTATO
IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'CONSULTA_CONTATO')
DROP PROCEDURE CONSULTA_CONTATO
GO

CREATE PROCEDURE CONSULTA_CONTATO(@PARAM VARCHAR(20) = null)
AS
BEGIN
  IF(@PARAM IS NULL)
     SELECT 
		C.ID_CONTATO, C.NOME_CONTATO, E.ID_EMAIL AS ID, E.EMAIL AS DSC, 1 AS TIP 
   FROM 
		TB_EMAIL E 
		JOIN TB_CONTATOS C ON E.ID_CONTATO = C.ID_CONTATO
   UNION ALL
   SELECT 
		C.ID_CONTATO, C.NOME_CONTATO, T.ID_TELEFONE, T.TELEFONE, 2 AS TIP
   FROM 
		TB_TELEFONE T 
		JOIN TB_CONTATOS C ON T.ID_CONTATO = C.ID_CONTATO 
  ELSE
   SELECT 
		C.ID_CONTATO, C.NOME_CONTATO, E.ID_EMAIL AS ID, E.EMAIL AS DSC, 1 AS TIP 
   FROM 
		TB_EMAIL E 
		JOIN TB_CONTATOS C ON E.ID_CONTATO = C.ID_CONTATO
   WHERE 
		E.EMAIL LIKE '%'+@PARAM+'%' OR C.NOME_CONTATO LIKE '%'+@PARAM+'%'
   UNION ALL
   SELECT 
		C.ID_CONTATO, C.NOME_CONTATO, T.ID_TELEFONE, T.TELEFONE, 2 AS TIP
   FROM 
		TB_TELEFONE T 
		JOIN TB_CONTATOS C ON T.ID_CONTATO = C.ID_CONTATO 
   WHERE 
		T.TELEFONE LIKE '%'+@PARAM+'%' OR C.NOME_CONTATO LIKE '%'+@PARAM+'%'
	
END
GO


