--PROCEDURE DELETE CONTATO
IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'DELETE_CONTATO')
DROP PROCEDURE DELETE_CONTATO
GO

CREATE PROCEDURE DELETE_CONTATO(@ID_CONTATO INT)
AS
BEGIN
    DECLARE  @CONTATO_INT INT
	DECLARE @RET_VALUE INT
	SET @CONTATO_INT = (SELECT COUNT(*) FROM TB_CONTATOS WHERE ID_CONTATO = @ID_CONTATO)
	IF(@CONTATO_INT = 0)
	BEGIN
	   SET @RET_VALUE = -1
    END
	ELSE
	BEGIN TRY
	    DELETE FROM TB_CONTATOS WHERE ID_CONTATO =  @ID_CONTATO
		SET @RET_VALUE = @ID_CONTATO
	END TRY
	BEGIN CATCH
	    SET @RET_VALUE = 0 
	END CATCH
END
GO

--PROCEDURE DELETE EMAIL
IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'DELETE_EMAIL')
DROP PROCEDURE DELETE_EMAIL
GO

CREATE PROCEDURE DELETE_EMAIL(@ID_EMAIL INT)
AS
BEGIN
    DECLARE  @EMAIL_INT INT
	DECLARE @RET_VALUE INT
	SET @EMAIL_INT = (SELECT COUNT(*) FROM TB_EMAIL WHERE ID_EMAIL = @ID_EMAIL)
	IF(@EMAIL_INT = 0)
	BEGIN
	   SET @RET_VALUE = -1
    END
	ELSE
	BEGIN TRY
	    DELETE FROM TB_EMAIL WHERE ID_EMAIL = @ID_EMAIL
		SET @RET_VALUE = @ID_EMAIL
	END TRY
	BEGIN CATCH
	    SET @RET_VALUE = 0 
	END CATCH
END
GO

--PROCEDURE DELETE TELEFONE
IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'DELETE_TELEFONE')
DROP PROCEDURE DELETE_TELEFONE
GO

CREATE PROCEDURE DELETE_TELEFONE(@ID_TELEFONE INT)
AS
BEGIN
    DECLARE  @TELEFONE_INT INT
	DECLARE @RET_VALUE INT
	SET @TELEFONE_INT = (SELECT COUNT(*) FROM TB_TELEFONE WHERE ID_TELEFONE = @ID_TELEFONE)
	IF(@TELEFONE_INT = 0)
	BEGIN
	   SET @RET_VALUE = -1
    END
	ELSE
	BEGIN TRY
	    DELETE FROM TB_TELEFONE WHERE ID_TELEFONE = @ID_TELEFONE
		SET @RET_VALUE=  @ID_TELEFONE
	END TRY
	BEGIN CATCH
	    SET @RET_VALUE = 0 
	END CATCH
END
GO


--PROCEDURE DELETE EMAIL/TELEFONE
IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'DELETE_EMAILTELEFONE')
DROP PROCEDURE DELETE_EMAILTELEFONE
GO

CREATE PROCEDURE DELETE_EMAILTELEFONE(@ID_CONTATO INT)
AS
BEGIN
    DECLARE  @CONTATO_INT INT
	DECLARE @RET_VALUE INT
	SET @CONTATO_INT = (SELECT COUNT(*) FROM TB_TELEFONE WHERE ID_CONTATO = @ID_CONTATO)
	IF(@CONTATO_INT = 0)
	BEGIN
	   SET @RET_VALUE = -1
    END
	ELSE
	BEGIN TRY
	    DELETE FROM TB_EMAIL WHERE ID_CONTATO = @ID_CONTATO
		DELETE FROM TB_TELEFONE WHERE ID_CONTATO = @ID_CONTATO
		SET @RET_VALUE =  @ID_CONTATO
	END TRY
	BEGIN CATCH
	    SET @RET_VALUE = 0 
	END CATCH
END
GO