CREATE TABLE TB_CONTATOS(
 ID_CONTATO INT IDENTITY(1,1) PRIMARY KEY,
 NOME_CONTATO VARCHAR(100)  NOT NULL
);

CREATE TABLE TB_EMAIL(
  ID_EMAIL INT IDENTITY(1,1) PRIMARY KEY,
  ID_CONTATO INT NOT NULL,
  EMAIL VARCHAR(200)  NOT NULL
);

CREATE TABLE TB_TELEFONE(
  ID_TELEFONE INT IDENTITY(1,1) PRIMARY KEY,
  ID_CONTATO INT NOT NULL,
  TELEFONE VARCHAR(14)  NOT NULL
);

