--PROCEDURE INSERT CONTATO
IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'INSERT_CONTATO')
DROP PROCEDURE INSERT_CONTATO
GO

CREATE PROCEDURE INSERT_CONTATO(@NOME_CONTATO VARCHAR(100))
AS
BEGIN
    DECLARE  @NOME_INT INT
	DECLARE  @RET_VALUE INT
	SET @NOME_INT = (SELECT COUNT(*) FROM TB_CONTATOS WHERE NOME_CONTATO = @NOME_CONTATO)
	IF(@NOME_INT > 0)
	BEGIN
	   SET @RET_VALUE = -1
    END
	ELSE
	BEGIN TRY
	    INSERT INTO TB_CONTATOS(NOME_CONTATO) VALUES(@NOME_CONTATO)
		SET @RET_VALUE = (SELECT @@IDENTITY)
	END TRY
	BEGIN CATCH
	    SET @RET_VALUE = 0 
	END CATCH
END
GO

--PROCEDURE INSERT EMAIL
IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'INSERT_EMAIL')
DROP PROCEDURE INSERT_EMAIL
GO

CREATE PROCEDURE INSERT_EMAIL(@EMAIL VARCHAR(200), @ID_CONTATO INT)
AS
BEGIN
    DECLARE  @EMAIL_INT INT
	DECLARE  @RET_VALUE INT
	SET @EMAIL_INT = (SELECT COUNT(*) FROM TB_EMAIL WHERE EMAIL = @EMAIL AND ID_CONTATO = @ID_CONTATO)
	IF(@EMAIL_INT > 0)
	BEGIN
	   SET @RET_VALUE = -1
    END
	ELSE
	BEGIN TRY
	    INSERT INTO TB_EMAIL(ID_CONTATO, EMAIL) VALUES(@ID_CONTATO, @EMAIL)
		SET @RET_VALUE = (SELECT @@IDENTITY)
	END TRY
	BEGIN CATCH
	    SET @RET_VALUE = 0 
	END CATCH
END
GO

--PROCEDURE INSERT TELEFONE
IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'INSERT_TELEFONE')
DROP PROCEDURE INSERT_TELEFONE
GO

CREATE PROCEDURE INSERT_TELEFONE(@TELEFONE VARCHAR(14), @ID_CONTATO INT)
AS
BEGIN
    DECLARE  @TELEFONE_INT INT
	DECLARE  @RET_VALUE INT
	SET @TELEFONE_INT = (SELECT COUNT(*) FROM TB_TELEFONE WHERE TELEFONE = @TELEFONE AND ID_CONTATO = @ID_CONTATO)
	IF(@TELEFONE_INT > 0)
	BEGIN
	   SET @RET_VALUE = -1
    END
	ELSE
	BEGIN TRY
	    INSERT INTO TB_TELEFONE(ID_CONTATO, TELEFONE) VALUES(@ID_CONTATO, @TELEFONE)
		 SET @RET_VALUE = (SELECT @@IDENTITY)
	END TRY
	BEGIN CATCH
	     SET @RET_VALUE = 0 
	END CATCH
END